### ISSUE TITLE
home.js hard to read / messy

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/Asky#11]
https://github.com/WebAhead7/Asky/blob/main/public/home.js

it's a really messy file would be nice if there was more empty lines between lines of code and comments maybe

**Comment by Karyum** [comment]
also this file is empty 
https://github.com/WebAhead7/Asky/blob/main/public/questions.js

**Comment by rakad-kh** [comment]
added some empty lines between, and deleted questions.js file.
