### ISSUE TITLE
your code is injected by the user

### ISSUE THREAD

**Issue by Ammaryus** [WebAhead7/Asky#5]
I think you used innerHtml in your code , if you try to answer any question by inserting the following string you will figure out 
the problem , insert `<img src='hh.png' onerror ='alert("hello")'/>` in any text

**Comment by Karyum** [comment]
ughh you broke the website.... 😆

**Comment by Ammaryus** [comment]
Sorry ..

**Comment by halaassaly** [comment]
Ammar the injection master!! thank you for the notice you  we will definetly learn from it and prevent it in our next projects..
